# Generated by Django 5.2.1 on 2025-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteMitra', '0003_alter_syllabus_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='pdf_url',
            field=models.URLField(default='untitled'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(upload_to='temp_uploads/'),
        ),
    ]
