# Generated by Django 5.2.1 on 2025-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteMitra', '0004_remove_syllabus_pdf_file_note_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
