# Generated by Django 5.2.1 on 2025-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteMitra', '0005_alter_note_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(default='default', upload_to='temp_uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
